config/routes.rb
Refinery::Core::Engine.routes.prepend do
  get '/about-us', :to => 'pages#about_us', :as => :about_us
  get '/news/services/hotels', :to => 'Hotels::Hotels#index'
  get '/news/services/hotels/:id', :to => 'Hotels::Hotels#show'
  get '/audience/services/hotels', :to => 'Hotels::Hotels#index'
  get '/audience/services/hotels/:id', :to => 'Hotels::Hotels#show'
  get '/news/corp_partners', :to => 'CorpPartners::CorpPartners#index'
  get '/media/cooperation', :to => 'Cooperations::Cooperations#index'
  get '/partners/visitors', :to => 'Exhibitors::Exhibitors#index'
end

MyNewApp::Application.routes.draw do

  resources :vipers

  resources :orders

  resources :stores
  get '/admin/stores', :to => 'Admin::Stores#index'
  post '/admin/stores', :to => 'Admin::Stores#create'
  get '/admin/stores/:id/edit', :to => 'Admin::Stores#edit'
  put    'admin/stores/:id', :to => 'Admin::Stores#update'
  delete '/admin/stores/:id', :to => 'Admin::Stores#destroy'
  get '/admin/stores/new', :to => 'Admin::Stores#new'
  get '/admin/stores/:id/editxy', :to => 'Admin::Stores#editxy'
  get '/admin/stores/:id', :to => 'Admin::Stores#show'

  get "booking/index"
  resources :line_items
  resources :carts
  resources :products
  resources :blanks

  mount Ckeditor::Engine => '/ckeditor'

  mount Refinery::Core::Engine, :at => '/'

end

app/models/store.rb
# 现在将展区当为Store
# x_no y_no 是代表行列 
# store 表是由客户自行填写

class Store < ActiveRecord::Base
  attr_accessible :name, :x_no, :y_no

  has_many :relations
  has_many :products, :through => :relations
end

app/controllers/admin/stores_controller.rb
module Admin
  class StoresController < ApplicationController
    # GET /stores
    # GET /stores.json
    before_filter :find_placeview_page, :set_cart, :set_products
    def index
      @stores = Store.all

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @stores }
      end
    end

    # GET /stores/1
    # GET /stores/1.json
    def show
      @store = Store.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @store }
      end
    end

    # GET /stores/new
    # GET /stores/new.json
    def new
      @store = Store.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @store }
      end
    end

    # GET /stores/1/edit
    def edit
      @store = Store.find(params[:id])
    end

    # POST /stores
    # POST /stores.json
    def create
      @store = Store.new(params[:store])

      respond_to do |format|
        if @store.save
          format.html { redirect_to "/admin/stores/"+@store.id.to_s(), notice: 'Store was successfully created.' }
          format.json { render json: @store, status: :created, location: @store }
        else
          format.html { render action: "new" }
          format.json { render json: @store.errors, status: :unprocessable_entity }
        end
      end
    end

    # PUT /stores/1
    # PUT /stores/1.json
    def update
      @store = Store.find(params[:id])


      @product = Product.find(params[:product_id]) unless (params[:product_id] == "zero" || params[:product_id].blank?)
      @x_c = params[:x_c].to_i
      @y_c = params[:y_c].to_i

      if params[:product_id] == "zero"
        r = Relation.where(:store_id => @store.id, :x_c => @x_c, :y_c => @y_c)
        r.destroy_all
      end

      unless @product.blank?
        r = Relation.where(:store_id => @store.id, :x_c => @x_c, :y_c => @y_c).first

        if r
          r.product_id = @product.id
          r.save!
        else
          r = Relation.new(store_id: @store.id, product_id: @product.id, x_c: @x_c, y_c: @y_c)
          r.save!
        end
      end

      params.delete(:product_id) if params.has_key?(:product_id)
      params.delete(:x_c) if params.has_key?(:x_c)
      params.delete(:y_c) if params.has_key?(:y_c)

      respond_to do |format|
        if @store.update_attributes(params[:store])
          format.html { redirect_to "/admin/stores/"+@store.id.to_s(), notice: 'Store was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @store.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /stores/1
    # DELETE /stores/1.json
    def destroy
      @store = Store.find(params[:id])
      @store.destroy

      respond_to do |format|
        format.html { redirect_to "/admin/stores" }
        format.json { head :no_content }
      end
    end

    def editxy
      @store = Store.find(params[:id])
    end

    def find_placeview_page
      @place_view_page = ::Refinery::Page.find("placeview")
    end

    def set_cart
      @cart = Cart.find(session[:cart_id])
    rescue ActiveRecord::RecordNotFound
      @cart = Cart.create
      session[:cart_id] = @cart.id
    end

    def set_products
      fiter = params[:place_name]
      @products = Product.where("number like '%#{fiter}%'")
    end
  end

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  # GET /stores
  # GET /stores.json
  before_filter :find_placeview_page, :set_cart
  def index
    @stores = Store.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stores }
    end
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
    @store = Store.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @store }
    end
  end

  # GET /stores/new
  # GET /stores/new.json
  def new
    @store = Store.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @store }
    end
  end

  # GET /stores/1/edit
  def edit
    @store = Store.find(params[:id])
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(params[:store])

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render json: @store, status: :created, location: @store }
      else
        format.html { render action: "new" }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stores/1
  # PUT /stores/1.json
  def update
    @store = Store.find(params[:id])


    @product = Product.find(params[:product_id]) unless params[:product_id].blank?
    @x_c = params[:x_c].to_i
    @y_c = params[:y_c].to_i

    params.delete(:product_id) if params.has_key?(:store_id)
    params.delete(:x_c) if params.has_key?(:x_c)
    params.delete(:y_c) if params.has_key?(:y_c)

    unless @product.blank?
      r = Relation.new(store_id: @store.id, product_id: @product.id, x_c: @x_c, y_c: @y_c)
      r.save!
    end

    respond_to do |format|
      if @store.update_attributes(params[:store])
        puts "---"*50
        puts "qwe"
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { head :no_content }
      else
        puts "---"*50
        format.html { render action: "edit" }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store = Store.find(params[:id])
    @store.destroy

    respond_to do |format|
      format.html { redirect_to stores_url }
      format.json { head :no_content }
    end
  end

  def find_placeview_page
    @place_view_page = ::Refinery::Page.find("placeview")
  end

  def set_cart
    @cart = Cart.find(session[:cart_id])
  rescue ActiveRecord::RecordNotFound
    @cart = Cart.create
    session[:cart_id] = @cart.id
  end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_for(@store) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :展区编号 %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :展区列数 %><br />
    <%= f.number_field :x_no %>
  </div>
  <div class="field">
    <%= f.label :展区行数 %><br />
    <%= f.text_field :y_no %>
  </div>
  <div class="actions">
    <%= f.submit "确定" %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing store</h1>

<%= render 'form' %>

<%= link_to '查看当前展区', @store %> |
<%= link_to '返回', stores_path %>

app/views/stores/index.html.erb
<h1>展区列表</h1>

<table>
  <tr>
    <th>展区编号</th>
    <th>展区的列数</th>
    <th>展区的行数</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stores.each do |store| %>
  <tr>
    <td><%= store.name %></td>
    <td><%= store.x_no %></td>
    <td><%= store.y_no %></td>
    <td><%= link_to '查看当前展区', store %></td>
    <td><%= link_to '编辑当前展区', edit_store_path(store) %></td>
    <td><%= link_to '删除当前展区', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to '增加新展区', new_store_path %>

app/views/stores/new.html.erb
<h1>添加展区</h1>

<%= render 'form' %>

<%= link_to '返回', stores_path %>

app/views/stores/show.html.erb
<script>
  <% if !current_refinery_user %>
    alert("请登录");
    window.location.href = "/";
  <% end %>
  <% if current_refinery_user&&!current_refinery_user.has_role?(:exhibitor) %>
    alert("请注册参展商用户，并提交参展申请");
    window.location.href = "/";
  <% end %>
  <% if current_refinery_user %>
    <% if !current_refinery_user.is_ex_certified %>
      var b_conf = confirm("您是未认证参展商用户，如需参展选位，请先提交参展申请，如已提交，请等待审核!");
      if (b_conf == true) {
        location.href = "/partners/apply";
      }else {
        location.href = "/";
      }
      return;
    <% end %>
  <% end %>
</script>
<div class='show_container store_body'>
  <div class='show_body'>
    <h1 id='body_content_title'><%=raw @place_view_page.title() %></h1>
    <section id='body'>
      <h3>已选展位<a class="back" href="<%= refinery.url_for(@place_view_page.url_marketable) %>"><img src="/assets/back.jpg"></a></h3>

      <div class="ordered_line_items" id="ordered_line_items" data-id="<%= @cart.id %>">
        <% if @cart.line_items.length > 0 %>
          <% @cart.line_items.each do |item| %>
            <div id="ordered_item_<%= item.product.id %>" data-id="<%= item.id %>"><%= item.product.number %></div>
          <% end %>
        <% else %>
          还没有选座，请点选下面座位，点击两次可取消
        <% end %>
      </div>
      <div class="order_btn">
        <a type="button" class="btn btn-warning btn-lg order">提交订单</a>
        <a type="button" class="btn btn-info btn-lg clear">清空订单</a>
      </div>

      <div class="margin-1"></div>

      <h3><%= @store.name %></h3>
      <div class="margin-1"></div>
      <!-- 展区详细坐标 -->
      图例：<span class="order-des white-des">该场地可预订</span> <span class="order-des blue-des">该场地已被选</span> <span class="order-des red-des">该场地已被预订</span>
      <div class="margin-1"></div>
      <div class="list_products">
        <input id="authenticity_token" name="authenticity_token" type="hidden" value="<%= form_authenticity_token() %>" >
        <% for i in 0..@store.y_no-1 %>
          <div class="row" style="width: <%= 47*(@store.x_no) %>px;">
            <% for j in 0..@store.x_no-1 %>
              <div id="xy_<%= j.to_s() + "_" + i.to_s() %>">

              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </section>
  </div>
</div>

<% content_for :stylesheets do %>
<% if @place_view_page.background_image.present? %>
<style type="text/css">
body {
  background: url(<%= @place_view_page.background_image.url -%>) no-repeat fixed;
  background-size:cover;
}
</style>
<% end %>
<% end %>

<% content_for :javascripts do %>
  <script>
  $(document).ready(function(){
    <% @store.products.each do |product| %>
      <% product.get_xy.each do |xy_c| %>
        <% if xy_c[0] == @store.id %>
          var xy_str = "<div class='product_item " + "<%= 'ordered' if product.status != 'free'%>" + "' data-proid='product_item_<%= product.id %>'" + " data-number='<%= product.number %>'>" + "<%= product.number %></div>";
          $("#xy_<%= xy_c[1].to_s() + "_" + xy_c[2].to_s() %>").html(xy_str);
        <% end %>
      <% end %>
    <% end %>
    if ($(".product_item").length > 0) {
      $(".ordered_line_items").children().each(function() {
        var ordered_line_product_id = $(this)[0].id.slice(13);
        var ordered_line_id = $(this)[0].dataset.id;
        $(".product_item").each(function() {
          if ($(this)[0].dataset.proid.slice(13) == ordered_line_product_id) {
            $(this).addClass("active");
            $(this)[0].dataset.id = ordered_line_id;
          }
        });
      });
      $(".product_item").click(function() {
        // console.log($("#current_user").length);
        if ($("#current_user").length == 0){
          $(".top-login-btn").trigger("click");
          return;
        }
        if ($("#current_user").length > 0){
          if (! $("#current_user").hasClass("rlsu")) {
            if (! $("#current_user").hasClass("rlex")) {
              alert("您不是参展商用户, 如需参展选位，请注册参展商用户");
              return;
            }else {
              <% if current_refinery_user %>
                <% if !current_refinery_user.is_ex_certified %>
                  var b_conf = confirm("您是未认证参展商用户，如需参展选位，请先提交参展申请，如已提交，请等待审核!");
                  if (b_conf == true) {
                    location.href = "/partners/apply";
                  }
                  return;
                <% end %>
              <% end %>
            }
          }
        }
        // console.log($("#current_user").length);
        var _this = this;
        var _this_colloct_id =  $(_this)[0].dataset.proid;
        var _this_colloct = $(".product_item").filter(function() {
          return this.dataset.proid == _this_colloct_id;
        });
        if ($(_this).hasClass("ordered")){
          return;
        }
        var postdata = {
          "product_id": $(this)[0].dataset.proid.slice(13)
        };
        var post_url = "/line_items";
        var post_type = 'post';
        if ($(_this).hasClass("active")) {
          post_url = "/line_items/" + $(this)[0].dataset.id;
          post_type = "delete";
          postdata = "";
        }
        $.ajax({
          url: post_url,
          type: post_type,
          dataType: 'json',
          data: JSON.stringify(postdata),
          headers: {
            'X-CSRF-Token': $("#authenticity_token").val()
          },
          processData: false,
          contentType: "application/json; charset=UTF-8",
          success: function(data) {
            if (_this_colloct.hasClass("active")) {
              _this_colloct.removeClass("active");
              var ordered_line_product_id = $(_this)[0].dataset.proid.slice(13);
              var ordered_line_id = $(_this)[0].dataset.id;
              $(".ordered_line_items").children().each(function() {
                if ($(this)[0].id.slice(13) == ordered_line_product_id) {
                  $(this)[0].remove();
                }
              });
              if ($(".ordered_line_items").children().length == 0) {
                var no_content_str = "还没有选座，请点选下面座位，点击两次可取消";
                $(".ordered_line_items").html(no_content_str);
              }
            } else {
              _this_colloct.addClass("active");
              var ordered_html = $(".ordered_line_items").html();
              if ($(".ordered_line_items").children().length == 0) {
                ordered_html = "";
              }
              _this_colloct.each(function() {
                this.dataset.id = data.id;
              });
              ordered_html += "<div id='ordered_item_" + $(_this)[0].dataset.proid.slice(13) + "' data-id='" + data.id +"'>" + $(_this)[0].dataset.number +"</div>";
              $(".ordered_line_items").html(ordered_html);
              $(".ordered_line_items")[0].dataset.id = data.cart_id;
            }
          },
          error: function(errors){
            alert("系统繁忙，请稍后再试");
          }
        });


      });
    }

  });
  </script>
<% end %>