config/routes.rb
Refinery::Core::Engine.routes.prepend do
  get '/about-us', :to => 'pages#about_us', :as => :about_us
  get '/news/services/hotels', :to => 'Hotels::Hotels#index'
  get '/news/services/hotels/:id', :to => 'Hotels::Hotels#show'
  get '/audience/services/hotels', :to => 'Hotels::Hotels#index'
  get '/audience/services/hotels/:id', :to => 'Hotels::Hotels#show'
  get '/news/corp_partners', :to => 'CorpPartners::CorpPartners#index'
  get '/media/cooperation', :to => 'Cooperations::Cooperations#index'
  get '/partners/visitors', :to => 'Exhibitors::Exhibitors#index'
end

MyNewApp::Application.routes.draw do

  resources :vipers

  resources :orders

  resources :stores
  get '/admin/stores', :to => 'Admin::Stores#index'
  post '/admin/stores', :to => 'Admin::Stores#create'
  get '/admin/stores/:id/edit', :to => 'Admin::Stores#edit'
  put    'admin/stores/:id', :to => 'Admin::Stores#update'
  delete '/admin/stores/:id', :to => 'Admin::Stores#destroy'
  get '/admin/stores/new', :to => 'Admin::Stores#new'
  get '/admin/stores/:id/editxy', :to => 'Admin::Stores#editxy'
  get '/admin/stores/:id', :to => 'Admin::Stores#show'

  get "booking/index"
  resources :line_items
  resources :carts
  resources :products
  resources :blanks

  mount Ckeditor::Engine => '/ckeditor'

  mount Refinery::Core::Engine, :at => '/'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  # attr_accessible :title, :body
  # 如果删除了当前的Cart 那么与之相关联的line_items都会删掉
  has_many :line_items, dependent: :destroy
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    @cart = Cart.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(params[:cart])
    @cart.add_line_items_from_cart()

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil;

    respond_to do |format|
      format.html { redirect_to booking_index_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @carts.each do |cart| %>
  <tr>
    <td><%= link_to 'Show', cart %></td>
    <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
    <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<h2>您当前的购物车</h2>

<table>
  <%= render(@cart.line_items) %>
</table>

<%= button_to 'Empty cart', @cart, method: :delete, data: { confirm: 'Are you sure?'} %>