config/routes.rb
Refinery::Core::Engine.routes.prepend do
  get '/about-us', :to => 'pages#about_us', :as => :about_us
  get '/news/services/hotels', :to => 'Hotels::Hotels#index'
  get '/news/services/hotels/:id', :to => 'Hotels::Hotels#show'
  get '/audience/services/hotels', :to => 'Hotels::Hotels#index'
  get '/audience/services/hotels/:id', :to => 'Hotels::Hotels#show'
  get '/news/corp_partners', :to => 'CorpPartners::CorpPartners#index'
  get '/media/cooperation', :to => 'Cooperations::Cooperations#index'
  get '/partners/visitors', :to => 'Exhibitors::Exhibitors#index'
end

MyNewApp::Application.routes.draw do

  resources :vipers

  resources :orders

  resources :stores
  get '/admin/stores', :to => 'Admin::Stores#index'
  post '/admin/stores', :to => 'Admin::Stores#create'
  get '/admin/stores/:id/edit', :to => 'Admin::Stores#edit'
  put    'admin/stores/:id', :to => 'Admin::Stores#update'
  delete '/admin/stores/:id', :to => 'Admin::Stores#destroy'
  get '/admin/stores/new', :to => 'Admin::Stores#new'
  get '/admin/stores/:id/editxy', :to => 'Admin::Stores#editxy'
  get '/admin/stores/:id', :to => 'Admin::Stores#show'

  get "booking/index"
  resources :line_items
  resources :carts
  resources :products
  resources :blanks

  mount Ckeditor::Engine => '/ckeditor'

  mount Refinery::Core::Engine, :at => '/'

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  attr_accessible :product, :cart

  belongs_to :product
  belongs_to :cart
  belongs_to :order
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  # GET /line_items
  # GET /line_items.json

  before_filter :set_cart, only: [:create]
  before_filter :set_line_item, only: [:show, :edit, :update, :destroy]

  def index
    @line_items = LineItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @line_items }
    end
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @line_item }
    end
  end

  # GET /line_items/new
  # GET /line_items/new.json
  def new
    @line_item = LineItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @line_item }
    end
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    product = Product.find(params[:product_id])
    @line_item = @cart.line_items.build(product: product)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to @line_item.cart, notice: 'Line item was successfully created.' }
        format.json { render json: @line_item, status: :created, location: @line_item }
      else
        format.html { render action: "new" }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /line_items/1
  # PUT /line_items/1.json
  def update

    respond_to do |format|
      if @line_item.update_attributes(params[:line_item])
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy

    respond_to do |format|
      format.html { redirect_to line_items_url }
      format.json { head :no_content }
    end
  end

  private

  def set_line_item
    @line_item = LineItem.find(params[:id])
  end

  def set_cart
    @cart = Cart.find(session[:cart_id])
  rescue ActiveRecord::RecordNotFound
    @cart = Cart.create
    session[:cart_id] = @cart.id
  end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product %><br />
    <%= f.text_field :product %>
  </div>
  <div class="field">
    <%= f.label :cart %><br />
    <%= f.text_field :cart %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<tr>
  <td>
    <%= line_item.product.number %>
  </td>
</tr>

app/views/line_items/edit.html.erb
<h1>Editing line_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<h1>Listing line_items</h1>

<table>
  <tr>
    <th>Product</th>
    <th>Cart</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @line_items.each do |line_item| %>
  <tr>
    <td><%= line_item.product.id if line_item.product %></td>
    <td><%= line_item.cart.id if line_item.cart %></td>
    <td><%= link_to 'Show', line_item %></td>
    <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
    <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New line_item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Product:</b>
  <%= @line_item.product %>
</p>

<p>
  <b>Cart:</b>
  <%= @line_item.cart %>
</p>


<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>